about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

posts/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path("new/", views.new_post, name="new"),
    path("group/<slug:slug>/", views.group_posts, name="group"),
    path("", views.index, name="index"),
    path('<str:username>/', views.profile, name='profile'),
    path('<str:username>/<int:post_id>/', views.post_view, name='post'),
    path(
        '<str:username>/<int:post_id>/edit/',
        views.post_edit,
        name='post_edit',
    )
]

users/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path("signup/", views.SignUp.as_view(), name = "signup")
]

yatube/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    path("admin/", admin.site.urls),
    path("about/", include("about.urls", namespace='about')),
    path("", include("posts.urls"))
]

about/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.contrib.auth import get_user_model
from django.db import models


User = get_user_model()


class Group(models.Model):
    """Define elements for each group and their appearance."""
    title = models.CharField(
        verbose_name='название',
        max_length=200,
        help_text='введите название группы.',
    )
    description = models.TextField(verbose_name='описание')
    slug = models.SlugField(
        verbose_name='слаг',
        unique=True,
        help_text=('Слаг должен быть уникальным. Используйье только '
                   'латиницу, цифры, дефисы и знаки подчёркивания.'),
    )

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        verbose_name='текст',
        help_text='Напишите текст Вашей новой записи. Это обязательно.',
    )
    pub_date = models.DateTimeField("date published", auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="posts",
    )
    group = models.ForeignKey(
        Group,
        verbose_name='группа',
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name="posts",
        help_text='Выберите группу. Это необязательно.',
    )

    class Meta:
        ordering = ("-pub_date",)

    def __str__(self):
        return self.text[:15]

users/models.py
from django.db import models

# Create your models here.

posts/forms.py
from django.forms import ModelForm

from .models import Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['text', 'group']

users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import PostForm
from .models import Group, Post, User


def index(request):
    """Return 10 posts per page beginning from last."""
    post_list = Post.objects.select_related('group')
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    context = {"page": page, "paginator": paginator}
    return render(request, "index.html", context)


def group_posts(request, slug):
    """Return 10 posts per page in group beginning from last."""
    group = get_object_or_404(Group, slug=slug)
    group_post_list = group.posts.all()
    paginator = Paginator(group_post_list, 10)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    context = {
        "group": group,
        "page": page,
        "paginator": paginator,
    }
    return render(request, "group.html", context)


@login_required
def new_post(request):
    form = PostForm(request.POST or None)
    if request.method == 'POST' and form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        form.save()
        return redirect('/')
    context = {'form': form, 'is_edit': False}
    return render(request, 'posts/new.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    author_posts_list = author.posts.all()
    paginator = Paginator(author_posts_list, 10)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    posts_count = author.posts.count()
    context = {
        "page": page,
        "author": author,
        "paginator": paginator,
        "posts_count": posts_count,
    }
    return render(request, 'profile.html', context)


def post_view(request, username, post_id):
    author = get_object_or_404(User, username=username)
    post = get_object_or_404(Post, author__username=username, id=post_id)
    posts_count = author.posts.count()
    context = {
        "post": post,
        "posts_count": posts_count,
        "author": author,
    }
    return render(request, 'post.html', context)


def post_edit(request, username, post_id):
    post = get_object_or_404(Post, author__username=username, id=post_id)
    if request.user != post.author:
        return redirect('post', username=username, post_id=post_id)
    form = PostForm(data=request.POST or None, instance=post)
    if request.method == 'POST' and form.is_valid():
        form.save()
        return redirect('post', username=username, post_id=post_id)
    context = {
        "form": form,
        "is_edit": True,
        "post": post,
    }
    return render(request, 'posts/new.html', context)

users/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CreationForm


class SignUp(CreateView):
    """Define appearance and url for form based on User model"""
    form_class = CreationForm
    success_url = reverse_lazy('index')
    template_name = 'signup.html'

templates/about/author.html
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
{% load user_filters %}
   <main role="main" class="container">
      <div class="row">

          <div class="col-md-3 mb-3 mt-1">
              <div class="card">
                  <div class="card-body">
                      <ul class="list-group list-group-flush">
                          <li class="list-group-item">
                              <div class="h3">
                                Об авторе
                              </div> 
                          </li>
                          <li class="list-group-item">
                              <div class="h6 text-muted">
                              Ильдус Исламов
                              г.Уфа
                              </div>
                          </li>
                      </ul>                                               
                  </div>                    
              </div>                
          </div>

          <div class="col-md-9">
              <div class="card-body">                    
                  <div class="card-text">
                      <p>Автор сие работы весьма немногословен. Ильдус Исламов, из города Уфа. Люблю, когда нравится что-то )). Вот научусь, и тут слева появится красивая картинка.</p>
                  </div>                    
              </div>                
          </div>            
      </div>        
  </main>
{% endblock %}

templates/about/tech.html
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block content %}
{% load user_filters %}
  <main role="main" class="container">
      <div class="row">

          <div class="col-md-3 mb-3 mt-1">
              <div class="card">
                  <div class="card-body">
                      <ul class="list-group list-group-flush">
                          <li class="list-group-item">
                              <div class="h3">
                                  Технологии
                              </div> 
                          </li>
                          <li class="list-group-item">
                              <div class="h6 text-muted">
                                  <p>Что я знаю о технологиях?</p>
                                  <p>А о технологиях Django? </p>
                                  <p>Верно, ничего. Но все-таки из этого я немножечко выжал...</p>
                              </div>
                          </li>
                      </ul>                                               
                  </div>                    
              </div>                
          </div>

          <div class="col-md-9">
              <div class="card-body">                    
                  <div class="card-text">
                    <style>p {text-align: justify; text-indent: 25px;}</style>  
			<p>Джанго, конечно, божественен, логически божественен! Не имею ни крупинки опыта в создании сайта и кодинга Ваш покорный автор посмел бросить вызов и пошел в наступление на самого Джанго!</p>
		<p>И снаряжение позволяло, я ничего не боялся: у меня был молоток с удобнейшей деревянной рукояткой, 2 (Карл, две!) пилы - с малыми зубцами для тонкой работы и острыми крупными для твердого дерева. Сокровенный ящик содержал все лучшее, что создано человечеством на сегодня:
		шурупы черные, саморезы, дюпель-гвозди на 6 (куда без них!), болт-гайка и все в паре да еще и с шайбой. За спиной перфоратор на 750 Вт, дрель на аккумуляторной батарее (с запасной в комплекте, все продумано). Встреча могла сулить неслабые разряды - и здесь мне могли пригодиться 
		СИНЯЯ изолента, батарейки. И это не считая элитных артефактов по бокам и  в карманах: скотч, пласки, отвертки (такие и сякие). Боже, уже грозно! Да кого мы только не брали, хватало и половины артефактов!</p>
		<p>И тут ... встреча с Django, Python! Болты не вкручиваются, пила не знает с какой стороны пилить, скотч лепится во все стороны - никакого эффекта! В попытке взять хитростью молоток выскакивает с рук, последние шурупы впиваются в руки...боль! 
		<p>И на меня пошла орда джанговская: атрибуты, методы, фреймворки, циклы, дерзкие крики "это не питонячи! дай нам чистый код!", меня терзали ревьюверы и совесть, падали со всех сторон ошибки, фэйлы. Выждал паузу, взял в руки ее, ее самую - клаву, и пошел:</p>
		<p>- зарегился на GitHub, сфоркал нужные репозитарии;</p>
		<p>- установил Django, настроил окружение, создал проект, в нем сотворил приложения;</p>
		<p>- научился создавать модели, принимать и обрабатывать запросы GET и POST, готовить нужные данные через вьюху;</p>
		<p>- добавил форму, связал все это с шаблонами (которые создавались и с помощью bootstrap);</p>
		<p>- прогнал тесты, потом сам же их и создал, по крайней мере попытался - раны остались глубокие и все еще заживают, здесь была сильная борьба и она не закончена;</p>
		<p>- и какой я footer.html сделал, какой четкий получился валидатор;</p>
		<p>- прокачал целый левел по декораторам.</p>
		И стали силы выравниваться, и помощь наставников подоспела! Недельку отдохнем, и дальше, где рождаются технологии - туда, именно туда!
		      </p>
                  </div>                    
              </div>                
          </div>            
      </div>        
  </main>
{% endblock %}

templates/base.html
<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}The Last Social Media You'll Ever Need{% endblock %} | Yatube</title>
    <!-- Загрузка статики -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
    <script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
</head>

<body>
    <header>
    {% include 'nav.html' %}
    <div class="container">
    <h1>{% block header %}{% endblock %}</h1>
    </div>
    </header>

    <main>
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </main>
    {% include 'footer.html' %}   
</body>

</html> 

templates/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <p class="m-0 text-dark text-center ">
  <a href="{% url 'about:author' %}">Об авторе</a>
  <a href="{% url 'about:tech' %}">Технологии</a>
  </p>
<p class="m-0 text-dark text-center ">Социальная сеть <span style="color:red">Ya</span>tube © {% now "Y" %}, все права защищены.</p>
</footer>

templates/group.html
{% extends "base.html" %}
{% block title %}Записи сообщества {{ group.title }}{% endblock %}
{% block content %}
    <h1>{{ group.title }}</h1>
    <p>
        {{ group.description }}
    </p>
    {% for post in page %}
    <h3>
        Автор: {{ post.author.get_full_name }},
        дата публикации: {{ post.pub_date|date:"d M Y" }}
    </h3>
    <p>{{ post.text|linebreaksbr }}</p>
    <hr>
    {% endfor %}

   {% include "paginator.html" %}

{% endblock %}

templates/index.html
{% extends "base.html" %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block header %}Последние обновления на сайте{% endblock %}
{% block content %}

    {% for post in page %}
    <h3>
        Автор: {{ post.author.get_full_name }},
        Дата публикации: {{ post.pub_date|date:"d M Y" }}
    </h3>
    <p>{{ post.text|linebreaksbr }}</p>
    {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}

    {% include "paginator.html" %}

{% endblock %} 

templates/nav.html
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
    <a class="navbar-brand" href="/"><span style="color:red">Ya</span>tube</a>
    <nav class="my-2 my-md-0 mr-md-3">
        {% if user.is_authenticated %}
        Пользователь: {{ user.username }}.
        <a class="p-2 text-dark" href="{% url 'new' %}">Новая запись</a>
        <a class="p-2 text-dark" href="{% url 'password_change' %}">Изменить пароль</a>
        <a class="p-2 text-dark" href="{% url 'logout' %}">Выйти</a>
        {% else %}
        <a class="p-2 text-dark" href="{% url 'login' %}">Войти</a> |
        <a class="p-2 text-dark" href="{% url 'signup' %}">Регистрация</a>
        {% endif %}
    </nav>
</nav>

templates/paginator.html
{% if page.has_other_pages %}
<nav>
  <ul class="pagination">
    {% if page.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.previous_page_number }}">&laquo; Предыдущая</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">&laquo; Предыдущая</span>
    </li>
    {% endif %}
    {% for i in page.paginator.page_range %}
    {% if page.number == i %}
    <li class="page-item active">
      <span class="page-link">{{ i }}
        <span class="sr-only">(текущая)</span>
      </span>
    </li>
    {% else %}
    <li class="page-item">
      <a class="page-link" href="?page={{ i }}">{{ i }}</a>
    </li>
    {% endif %}
    {% endfor %}
    {% if page.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.next_page_number }}">Следующая &raquo;</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">Следующая &raquo;</span>
    </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

templates/post.html
{% extends "base.html" %}

{% block content %}
<main role="main" class="container">
    <div class="row">
            <div class="col-md-3 mb-3 mt-1">
                <div class="card">
                        <div class="card-body">
                                <div class="h2">
                                    {{ author.get_full_name }}
                                </div>
                                <div class="h3 text-muted">
                                     @{{ author.username }}
                                </div>
                        </div>
                        <ul class="list-group list-group-flush">
                                <li class="list-group-item">
                                        <div class="h6 text-muted">
                                        Подписчиков: XXX <br />
                                        Подписан: XXX
                                        </div>
                                </li>
                                <li class="list-group-item">
                                        <div class="h6 text-muted">
                                            Записей: {{ posts_count }}
                                        </div>
                                </li>
                        </ul>
                </div>
        </div>

        <div class="col-md-9">

                <div class="card mb-3 mt-1 shadow-sm">
                        <div class="card-body">
                                <p class="card-text">
                                        <a href="{% url 'profile' post.author %}"><strong class="d-block text-gray-dark">@{{ post.author }}</strong></a>
                                        {{ post.text }}
                                </p>
                                <div class="d-flex justify-content-between align-items-center">
                                        <div class="btn-group ">
                                                {% if user == post.author %}
                                                <a class="btn btn-sm text-muted" href="{% url 'post_edit' post.author post.id %}" role="button">Редактировать</a>
                                                {% endif %}
                                        </div>
                                        <small class="text-muted">{{ post.pub_date }}</small>
                                </div>
                        </div>
                </div>
     </div>
    </div>
</main>
{% include "paginator.html" %}

{% endblock %}

templates/posts/new.html
{% extends "base.html" %}
{% block title %}
                {% if is_edit %}
                Редактировать запись
                {% else %}
                Новая запись
                {% endif %}
{% endblock %} 
{% block header %}{% endblock %} 
{% block content %} 
 
<div class="row justify-content-center"> 
    <div class="col-md-8 p-5"> 
        <div class="card"> 
            <div class="card-header">
                {% if is_edit %}
                Редактировать запись
                {% else %}
                Новая запись
                {% endif %}         
            </div> 
            <div class="card-body"> 
 
                <form method="post"> 
                    {% csrf_token %} 
 
                    {% for field in form %} 
                    <div class="form-group row" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}> 
                        <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">{{ field.label }}{% if field.field.required %}<span class="required">*</span>{% endif %}</label> 
                        <div class="col-md-6"> 
                            {{ field }} 
                            {% if field.help_text %} 
                            <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small> 
                            {% endif %} 
                        </div> 
                </div> 
                    {% endfor %} 
 
                    <div class="col-md-6 offset-md-4">
                        <button type="submit" class="btn btn-primary">
                            {% if is_edit %}
                                Редактировать
                                {% else %}
                                Сохранить
                            {% endif %}
                            </button> 
                    </div> 
                </form> 
             </div> <!-- card body --> 
        </div> <!-- card --> 
    </div> <!-- col --> 
</div> <!-- row -->  
 
{% endblock %}  

templates/profile.html
{% extends "base.html" %}
{% block title %}Записи автора: {{ username.get_full_name }}{% endblock %}
{% block content %}
<main role="main" class="container">
        <div class="row">
                <div class="col-md-3 mb-3 mt-1">
                        <div class="card">
                                <div class="card-body">
                                        <div class="h2">
                                            {{ author.get_full_name }}
                                        </div>
                                        <div class="h3 text-muted">
                                                @{{ author.username }}
                                        </div>
                                </div>
                                <ul class="list-group list-group-flush">
                                        <li class="list-group-item">
                                                <div class="h6 text-muted">
                                                Подписчиков: XXX <br />
                                                Подписан: XXX
                                                </div>
                                        </li>
                                        <li class="list-group-item">
                                                <div class="h6 text-muted">
                                                    Записей: {{ posts_count }}
                                                </div>
                                        </li>
                                </ul>
                        </div>
                </div>
    
                <div class="col-md-9">                
    
                    {% for post in page %}
                        <div class="card mb-3 mt-1 shadow-sm">
                                <div class="card-body">
                                        <p class="card-text">
                                                <a href="{% url 'profile' post.author %}"><strong class="d-block text-gray-dark">@{{ post.author.username }}</strong></a>
                                                {{ post.text }}
                                        </p>
                                        <div class="d-flex justify-content-between align-items-center">
                                                <div class="btn-group ">
                                                        <a class="btn btn-sm text-muted" href="{% url 'post' post.author post.id %}" role="button">Добавить комментарий</a>
                                                        {% if user == post.author %}
                                                        <a class="btn btn-sm text-muted" href="{% url 'post_edit' post.author post.id %}" role="button">Редактировать</a>
                                                        {% endif %}
                                                </div>
                                                <small class="text-muted">{{ post.pub_date }}</small>
                                        </div>
                                </div>
                        </div>
                    {% endfor %}
        
                    {% include "paginator.html" %}
                </div>
        </div>
    </main>
{% endblock %}

users/templates/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
{% load user_filters %}

<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">Зарегистрироваться</div>
            <div class="card-body">
                
              {% for error in form.errors %}
                  <div class="alert alert-danger" role="alert">
                      {{ error|escape }}
                  </div>
                {% endfor %}

                <form method="post" action="{% url 'signup' %}">
                    {% csrf_token %}

                    {% for field in form %}
                        <div class="form-group row" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>
                                <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">{{ field.label }}{% if field.field.required %}<span class="required">*</span>{% endif %}</label>
                                <div class="col-md-6">

                                    {# подключаем фильтр и указываем класс #}
                                    {{ field|addclass:"form-control" }}

                                    {% if field.help_text %}
                                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                                    {% endif %}
                                </div>                
                        </div>
                    {% endfor %}

                    <div class="col-md-6 offset-md-4">              
                            <button type="submit" class="btn btn-primary">
                                Зарегистрироваться
                            </button>
                    </div>
                </form>
            </div> <!-- card body -->
        </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->

{% endblock %}